language: csharp
dist: trusty
mono: none
dotnet: 3.0.100
install:
- dotnet restore
script:
- dotnet build
- dotnet test ForumNet.Services.Tests/ForumNet.Services.Tests.csproj
- dotnet test ForumNet.Web.Tests/ForumNet.Web.Tests.csproj